### ISSUE TITLE
File does not get updated when the file is updated

### ISSUE THREAD

**Issue by dannythk** [maestrodev/puppet-wget#52] opened 2015-08-13 21:29 UTC
My code: 

wget::fetch { 'somefile':
    source      => "someURL",
    destination => "destFilePath/fileName",
    timeout     => 0,
    verbose     => false,
}

When I alter the destination file, puppet run does not revert my destination file back to the source file.
When I alter the source file, puppet run does not update my destination file with the latest update.
The only time it fetch for the file is when I remove the destination file....Is there a way that I could use this module to pull the file similar to "file" resource type?  I am not able to use the "File" resource because it is not located inside the Puppet master server.  

I also try to put in the cache_dir:

wget::fetch { 'somefile':
    source      => "someURL",
    destination => "$destFilePath/fileName",
    cache_dir   => '/var/cache/wget',
    timeout     => 0,
    verbose     => false,
}

Using the cache_dir works great!!  But if the source and destination files are identical, the "wget:fetch" still run as normal.  That would give Puppet a false alert that "something" change.

**Comment by johnzimm** [comment] 2015-08-17 20:07
I'm having the same issue.  Using the v1.7.0 release.

**Comment by carlossg** [comment] 2015-08-17 21:27
Using cache it calls wget with -P, you can get the full command line running puppet win debug mode and see if calling wget directly the behavior is the same. 
The way -P works is documented in http://www.gnu.org/software/wget/manual/wget.html#HTTP-Time_002dStamping-Internals

For the notification see #48

**Comment by johnzimm** [comment] 2015-08-18 22:32
I think I understand why this is happening I guess.  I can see the command line.  The behavior isn't what I initially expected.

I have the following snippet:

```puppet
wget::fetch { 'http://example.com/path/to/file':
  destination => '/local/path/to/file',
  cache_dir   => '/var/cache/wget',
}
```

This grabs the file fine and updates when the file is changed.  Except it execs / notifies every time the puppet agent runs.

Removing the cache_dir doesn't cause the subsequent notifications after the initial file placement, but also doesn't update the file when it is new on the web server.

Ultimately what I'm trying to mimic is if I were able to specify an http url in a file resource definition as if it were being delivered via the puppet file server or nfs.  It's likely this is just he wrong way to go about it.

In #48 subscribing to the resulting file in the wget::fetch definition gives me an error with Puppet 4.2 of "Error: Failed to apply catalog: Found 2 dependency cycles:".

**Comment by carlossg** [comment] 2015-08-19 09:46
the exec inside wget will always be executed to check if the remote file has changed, that's why it emits a refresh
In #48 it recommends to write your other code (NOT the wget:fetch) with a require to the file `File['/local/path/to/file']` so it only runs when the file changes

**Comment by carlossg** [comment] 2015-08-19 09:49
To sum up, file *does* get updated when the http file is updated, you just need to use `cache_dir` (or `redownload`, but that is inefficient)

This has become a dupe of #48, about how to subscribe to events when the file is updated

**Closed by carlossg** 2015-08-19 09:49 UTC
